// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW6ZS1Gl8UETDcWaNBvhtjsMvCjAOKQmA',
    appId: '1:414829410475:web:5e16b68be9314a64d19fee',
    messagingSenderId: '414829410475',
    projectId: 'notes-8bf54',
    authDomain: 'notes-8bf54.firebaseapp.com',
    storageBucket: 'notes-8bf54.appspot.com',
    measurementId: 'G-6FSLMJNP4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhI39dJp_1sZT7oVkqgFSMzAAABpKTsHE',
    appId: '1:414829410475:android:723d6900629002fad19fee',
    messagingSenderId: '414829410475',
    projectId: 'notes-8bf54',
    storageBucket: 'notes-8bf54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcFg3qlkM0bMqVFbXOF181WLVfVruyphk',
    appId: '1:414829410475:ios:7a971cb0296a97f5d19fee',
    messagingSenderId: '414829410475',
    projectId: 'notes-8bf54',
    storageBucket: 'notes-8bf54.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcFg3qlkM0bMqVFbXOF181WLVfVruyphk',
    appId: '1:414829410475:ios:0696ef2a8a6344d9d19fee',
    messagingSenderId: '414829410475',
    projectId: 'notes-8bf54',
    storageBucket: 'notes-8bf54.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
